apiVersion: v1
kind: Namespace
metadata:
  name: location-6
  annotations:
    configmanagement.gke.io/cluster-selector: loc-6-sel
    istio-injection: enabled istio.io/rev-
  labels:
    created-by: root-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
  annotations:
    configmanagement.gke.io/cluster-selector: loc-6-sel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - name: pos
        image: greavr/pos:v1.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pos-service
  namespace: pos
  annotations:
    configmanagement.gke.io/cluster-selector: loc-all
spec:
  type: LoadBalancer
  selector:
    app: pos
  ports:
  - name: http
    port: 80
    targetPort: 80
