###
###  This is an example of a working setup for multi-repo with proper comments
###

kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: chaos-azure-us-central  # NOTE: MUST MATCH spec.clusterName field in ConfigSManagment
  labels:
    location-name: "location-3"  # Should be unique in this situation (could be location number), used in selector
    canary: "50"
    location: "SC"
    market: "hipsters"
    equipment: "aks"
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: loc-3-sel
spec:
  selector:
    matchLabels:
      location-name: location-3 # label and value match Cluster label above
